# Generated by Django 5.0.4 on 2024-05-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Dificuldade',
            fields=[
                ('id_nivel_dificuldade', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Id nível dificuldade')),
                ('nm_nivel_dificuldade', models.CharField(max_length=30, unique=True, verbose_name='Nome nível dificuldade')),
                ('ds_nivel_dificuldade', models.CharField(max_length=100, null=True, verbose_name='Descrição dificuldade')),
                ('vl_nivel_dificuldade', models.IntegerField(default=0, null=True, verbose_name='Valor nível dificuldade')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Jogador',
            fields=[
                ('id_nivel_jogador', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Id nível jogador')),
                ('nm_nivel_jogador', models.CharField(max_length=30, unique=True, verbose_name='Nome nível jogador')),
                ('ds_nivel_jogador', models.CharField(max_length=100, null=True, verbose_name='Descrição nível jogador')),
                ('vl_nivel_jogador', models.IntegerField(default=0, null=True, verbose_name='Valor nível jogador')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Motivacao',
            fields=[
                ('tp_motivacao', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Sigla Motivação')),
                ('nm_motivacao', models.CharField(max_length=50, verbose_name='Motivação')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Recurso',
            fields=[
                ('tp_recurso', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Sigla Recurso')),
                ('nm_recurso', models.CharField(max_length=30, verbose_name='Motivação')),
            ],
        ),
    ]
