# Generated by Django 5.0.4 on 2024-05-16 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivacional',
            fields=[
                ('id_motivacao', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Id Idioma')),
                ('msg_motivacional', models.CharField(max_length=30, unique=True, verbose_name='Mensagem motivacional')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
                ('id_idioma', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.idioma', verbose_name='Idioma')),
                ('tp_motivacional', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogos.tipo_motivacao', verbose_name='Tipo motivação')),
            ],
        ),
    ]
