# Generated by Django 5.0.4 on 2024-05-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_motivacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id_jogo', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID jogo')),
                ('nm_jogo', models.CharField(max_length=30, unique=True, verbose_name='Nome jogo')),
                ('ds_jogo', models.CharField(max_length=100, null=True, verbose_name='Descrição jogo')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
            ],
        ),
    ]
