# Generated by Django 5.0.4 on 2024-05-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
        ('jogos', '0003_jogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id_frase', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Id frase')),
                ('ds_frase_idioma_1', models.CharField(max_length=100, unique=True, verbose_name='Frase idioma nativo')),
                ('ds_frase_idioma_2', models.CharField(max_length=100, verbose_name='Frase idioma aprendizado')),
                ('ds_frase_idioma_2_observacao', models.CharField(max_length=50, null=True, verbose_name='Frase idioma aprendizado')),
                ('nm_arquivo_imagem', models.CharField(max_length=50, null=True, verbose_name='Nome arquivo de imagem')),
                ('nm_arquivo_som', models.CharField(max_length=50, null=True, verbose_name='Nome arquivo de som')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
                ('id_idioma_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='frases_idioma_1', to='jogadores.idioma', verbose_name='Idioma nativo')),
                ('id_idioma_2', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='frases_idioma_2', to='jogadores.idioma', verbose_name='Idioma aprendizado')),
            ],
        ),
    ]
