# Generated by Django 5.0.4 on 2024-05-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0001_initial'),
        ('jogos', '0004_frase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbete',
            fields=[
                ('id_verbete', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Id verbete')),
                ('nm_verbete_idioma_2', models.CharField(max_length=100, unique=True, verbose_name='Verbete idioma aprendizado')),
                ('ds_verbete_idioma_1', models.CharField(max_length=100, verbose_name='Definição verbete idioma nativo')),
                ('nm_arquivo_imagem', models.CharField(max_length=50, null=True, verbose_name='Nome arquivo de imagem')),
                ('nm_arquivo_som', models.CharField(max_length=50, null=True, verbose_name='Nome arquivo de som')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inclusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
                ('id_idioma_1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='verbete_idioma_1', to='jogadores.idioma', verbose_name='Idioma nativo')),
                ('id_idioma_2', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='verbete_idioma_2', to='jogadores.idioma', verbose_name='Idioma aprendizado')),
            ],
        ),
    ]
