# Generated by Django 5.0.4 on 2024-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0008_alter_verbete_ds_verbete_idioma_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='ds_frase_idioma_1',
            field=models.CharField(max_length=200, unique=True, verbose_name='Frase idioma nativo'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='ds_frase_idioma_2',
            field=models.CharField(max_length=200, verbose_name='Frase idioma aprendizado'),
        ),
        migrations.AlterField(
            model_name='verbete',
            name='ds_verbete_idioma_1',
            field=models.CharField(max_length=300, verbose_name='Definição verbete idioma nativo'),
        ),
    ]
