# Generated by Django 5.0.4 on 2024-05-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0010_alter_frase_ds_frase_idioma_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbete',
            name='ds_verbete_idioma_1_observacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='ds_frase_idioma_1',
            field=models.CharField(max_length=250, unique=True, verbose_name='Frase idioma nativo'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='ds_frase_idioma_2',
            field=models.CharField(max_length=250, verbose_name='Frase idioma aprendizado'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='ds_frase_idioma_2_observacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='frase',
            name='nm_arquivo_imagem',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome arquivo de imagem'),
        ),
        migrations.AlterField(
            model_name='verbete',
            name='ds_verbete_idioma_1',
            field=models.CharField(max_length=250, verbose_name='Definição verbete idioma nativo'),
        ),
    ]
