# Generated by Django 5.0.4 on 2024-05-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id_escolaridade', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nm_escolaridade', models.CharField(max_length=30, unique=True)),
                ('ds_escolaridade', models.CharField(max_length=100, null=True)),
                ('vl_escolaridade', models.IntegerField(default=0, null=True)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inlusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID idioma')),
                ('nm_idioma', models.CharField(max_length=30, unique=True, verbose_name='Nome idioma')),
                ('ds_idioma', models.CharField(max_length=50, null=True, verbose_name='Descrição idioma')),
                ('nm_arquivo_imagem', models.CharField(max_length=50, null=True, verbose_name='Nome arquivo imagem')),
                ('nm_arquivo_estilo_css', models.CharField(max_length=50, null=True, verbose_name='Nome arquivo estilo CSS')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inlusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Genero',
            fields=[
                ('tp_genero', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Sigla Gênero')),
                ('nm_genero', models.CharField(max_length=30, verbose_name='Gênero')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id_jogador', models.AutoField(primary_key=True, serialize=False, verbose_name='Id jogador(a)')),
                ('nm_jogador', models.CharField(max_length=80, verbose_name='Nome Jogador(a)')),
                ('nm_avatar', models.CharField(max_length=20, unique=True, verbose_name='Nome Avatar')),
                ('nm_arquivo_imagem', models.CharField(max_length=50, null=True, verbose_name='Nome Arquivo Imagem')),
                ('dt_nascimento', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('cd_cep', models.CharField(max_length=8, null=True, verbose_name='CEP')),
                ('nm_email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('_nm_senha', models.CharField(db_column='nm_senha', max_length=20, null=True, verbose_name='Senha')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data inlusão')),
                ('id_usuario_inclusao', models.IntegerField(default=0, verbose_name='Usuário inclusao')),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('id_usuario_alteracao', models.IntegerField(default=0, null=True, verbose_name='Usuário alteração')),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data exclusão')),
                ('id_usuario_exclusao', models.IntegerField(default=0, null=True, verbose_name='Usuário exclusão')),
                ('id_escolaridade', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.escolaridade', verbose_name='Escolaridade')),
                ('id_idioma', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.idioma', verbose_name='Idioma')),
                ('tp_genero', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='jogadores.tipo_genero', verbose_name='Tipo gênero')),
            ],
        ),
    ]
