# Generated by Django 5.0.4 on 2024-05-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0002_alter_escolaridade_ds_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='ds_idioma',
            field=models.CharField(max_length=100, null=True, verbose_name='Descrição idioma'),
        ),
    ]
