# Generated by Django 5.0.4 on 2024-05-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0003_alter_idioma_ds_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escolaridade',
            name='ds_escolaridade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='ds_idioma',
            field=models.CharField(max_length=150, null=True, verbose_name='Descrição idioma'),
        ),
    ]
