# Generated by Django 5.0.4 on 2024-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogadores', '0004_alter_escolaridade_ds_escolaridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='nm_arquivo_imagem',
            field=models.CharField(max_length=50, null=True, verbose_name='Arquivo com imagem para Avatar'),
        ),
    ]
